using Azure;
using Azure.Data.Tables;
using Azure.Data.Tables.Models;
using System;
using System.IO;
using System.Linq;

namespace LAVersionReverter
{
    partial class Program
    {
        private static void GenerateTablePrefix(string LogicAppName, string WorkflowName, string ConnectionString)
        {
            string logicAppPrefix = StoragePrefixGenerator.Generate(LogicAppName.ToLower());

            //if we don't need to generate workflow prefix, just output Logic App prefix
            if (String.IsNullOrEmpty(WorkflowName))
            {
                Console.WriteLine($"Logic App Prefix: {logicAppPrefix}");

                return;
            }

            //The workflow prefix is generated by workflow ID which need to be retrieved from main table
            //So we need to have the connection string to be able to get workflow ID from storage table
            if (!String.IsNullOrEmpty(WorkflowName) && String.IsNullOrEmpty(ConnectionString))
            {
                Console.WriteLine("Please provide connection string when need to generate workflow prefix");

                return;
            }

            string mainTableName = GetMainTableName(LogicAppName, ConnectionString);

            TableClient tableClient = new TableClient(ConnectionString, mainTableName);
            Pageable<TableEntity> tableEntities = tableClient.Query<TableEntity>(filter: $"FlowName eq '{WorkflowName}'");

            if (tableEntities.Count() == 0)
            {
                Console.WriteLine("No workflow found in table, please double check the workflow name");
            }

            string workflowID = tableEntities.First<TableEntity>().GetString("FlowId");

            string workflowPrefix = StoragePrefixGenerator.Generate(workflowID);

            Console.WriteLine($"Logic App Prefix: {logicAppPrefix}");
            Console.WriteLine($"Workflow Prefix: {workflowPrefix}");
            Console.WriteLine($"Combined prefix: {logicAppPrefix}{workflowPrefix}");
        }
    }
}
